# Generated by Django 6.0.3 on 2026-04-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bus_amenities_company_address_company_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerdetail',
            name='fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='child_fare_pct',
            field=models.DecimalField(decimal_places=2, default=50, help_text='% of base fare for child tickets', max_digits=5),
        ),
        migrations.AddField(
            model_name='trip',
            name='child_max_age',
            field=models.PositiveIntegerField(default=12, help_text='Ages < 5 travel free; 5 to this age pays child_fare_pct'),
        ),
        migrations.AddField(
            model_name='trip',
            name='senior_fare_pct',
            field=models.DecimalField(decimal_places=2, default=80, help_text='% of base fare for senior tickets', max_digits=5),
        ),
        migrations.AddField(
            model_name='trip',
            name='senior_min_age',
            field=models.PositiveIntegerField(default=60, help_text='Ages >= this pay senior_fare_pct'),
        ),
    ]
