# Generated by Django 6.0.3 on 2026-04-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_age_pricing_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='luggage_charge_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Extra charge per kg above free allowance', max_digits=6),
        ),
        migrations.AddField(
            model_name='company',
            name='luggage_free_kg',
            field=models.PositiveIntegerField(default=15, help_text='Free luggage per passenger in kg'),
        ),
        migrations.AddField(
            model_name='trip',
            name='discount_label',
            field=models.CharField(blank=True, default='', help_text="Offer label shown to users, e.g. 'Diwali Special'", max_length=80),
        ),
        migrations.AddField(
            model_name='trip',
            name='discount_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount % on base price (0 = no offer)', max_digits=5),
        ),
    ]
