# Generated by Django 6.0.3 on 2026-05-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_add_discount_and_luggage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bus_images/'),
        ),
    ]
