# Generated by Django 6.0.3 on 2026-05-02 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_bus_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bus_gallery/')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='booking.bus')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
